import type { Project } from "./types";

export const projects = [
  {
    slug: "jarvis", index: "01", title: "JARVIS", shortTitle: "JARVIS", category: "Controlled Personal Agent Runtime",
    summary: "A local personal-agent host exploring when natural-language intent is allowed to become an operating-system side effect.",
    status: "active", accent: "cyan",
    metrics: [{ label: "Python suite", value: "889 passed", emphasis: true }, { label: "Skipped", value: "3" }, { label: "Conversation", value: "Persistent thread" }, { label: "Authorization", value: "Explicit operation" }],
    themes: ["Trust boundaries", "Protocol identity", "Authorization", "Deterministic testing"],
    dossier: {
      role: "Personal system engineering project",
      mission: "JARVIS explores how a local personal-agent host can delegate reasoning to Codex while preserving explicit remote authentication, user-visible authorization, cancellation, persistent conversation identity, and workspace-oriented execution boundaries.",
      technology: ["Python", "Codex App Server", "NDJSON", "SQLite", "Android client", "Typed runtime ports"],
      authorityStudy: {
        primaryQuestion: "When does intent become authority?",
        statusStatement: "Substantial local prototype // active development",
        overview: ["Natural-language intent, authenticated authorization, provider protocol state, local policy, and operating-system effects are separate concerns.", "The repository contains two architectural generations. Their guarantees are not interchangeable: the active Codex path is not governed universally by the foundational local ToolBroker.", "JARVIS does not claim to be production-ready, fully autonomous, or a completed general-purpose assistant."],
        activeFlow: ["Remote client", "Authenticated submit_agent_task", "RemoteGateway validation", "Opaque task UUID", "InMemoryRemoteTaskRunManager", "CodexBridgeRuntime", "Serialized persistent thread", "Codex App Server", "Reasoning + streaming", "Optional approval request", "Explicit authorize / cancel", "Complete / fail / cancel"],
        trustLayers: [
          { label: "Untrusted user input", detail: "Natural-language task or explicit remote operation", scope: "jarvis" },
          { label: "RemoteGateway", detail: "Exact fields · body size · UUIDs · aware timestamps · freshness · expiry · client identity · bearer token · replay", scope: "jarvis" },
          { label: "Task manager", detail: "Owner-bound handle · bounded streaming · cancellation bridge", scope: "jarvis" },
          { label: "CodexBridgeRuntime", detail: "Thread + turn matching · bridge generation · approval ownership · stale-event defense", scope: "jarvis" },
          { label: "Codex App Server", detail: "External tool discovery · tool validation · sandbox/tool layer · part of authorization", scope: "external" },
          { label: "OS / workspace / Git / network", detail: "Consequential side effects", scope: "effect" },
        ],
        authorizationChecks: ["Authenticated remote owner", "Current bridge generation", "Exact pending App Server request", "Approval expiry", "Single-decision state", "App Server response"],
        bridgeStates: ["IDLE", "STARTING", "WORKING", "WAITING_FOR_APPROVAL", "WORKING", "COMPLETED", "CANCELLING", "CANCELLED", "FAILED"],
        bridgeRecovery: "Protocol or subprocess failure triggers a recovery attempt and persistent-thread resume; the bridge returns to STARTING / WORKING or terminates as FAILED. Only one active bridge turn is allowed.",
        runtimes: [
          { label: "Active Codex-backed path", status: "Primary active path", description: "JARVIS authenticates the remote operation, owns task and protocol state, and mediates approval requests surfaced by Codex App Server. Tool inventory, tool validation, sandboxing, and part of authorization remain external.", steps: ["RemoteGateway", "InMemoryRemoteTaskRunManager", "CodexBridgeRuntime", "Codex App Server", "Codex-controlled tools", "OS / workspace"] },
          { label: "Foundational local runtime", status: "Implemented + tested // not primary", description: "This path demonstrates the local model-proposes / runtime-validates / policy-decides boundary.", steps: ["AgentRunId", "ModelProvider.complete", "ModelFinal or typed ModelToolProposal", "ProposalId + argument + limit validation", "ToolCallRequest", "ToolBroker", "Trusted ToolDefinition", "Argument normalization", "DefaultPolicy", "Resolve only after allow", "Execute + audit", "Bounded observation", "Next model turn or final"], limitation: "Successful tool output is not currently returned to the model; only status and error information continue the foundational loop." },
        ],
        boundaries: [
          { label: "Workspace containment", status: "Local path", items: ["filesystem.list", "filesystem.read", "filesystem.write", "filesystem.delete"], safeguards: ["Reject absolute paths", "Reject explicit .. segments", "Canonical resolution", "Workspace ancestry check", "Existing symlink target containment"], limitations: ["Windows symlink escape test skipped on forensic host", "Junction/reparse coverage incomplete", "Possible normalize-to-execute TOCTOU race", "No comprehensive resource limits"] },
          { label: "Shell boundary", status: "Authorization boundary ≠ sandbox", items: ["shell.execute", "Structured argv", "shell=False", "Canonical workspace cwd", "Timeout capped at 30 seconds", "stdout / stderr / exit capture"], safeguards: ["DefaultPolicy returns REQUIRE_APPROVAL", "No execution under default path because approval resumption is absent", "Timeout and nonzero exit map to safe failures"], limitations: ["No executable allowlist or path restriction", "No sanitized environment or output bound", "No network/filesystem sandbox", "No proven descendant-tree termination", "No universal cancellation propagation"] },
          { label: "Git boundary", status: "Three distinct realities", items: ["Broker: status / diff / log — read only", "Remote dispatcher: git.status only", "Governed service: prepare / verify / apply / optional local commit — dormant", "No push"], safeguards: ["Governed: exact top-level + clean tree", "Patch ≤128 KiB and ≤16 files", "No traversal, .git, binary, submodule, symlink or sensitive-file changes", "Fixed pytest / Ruff / mypy / diff verification", "Separate authorization before commit"], limitations: ["Governed workflow is not active in server.main", "Current dirty JARVIS tree would fail its clean-tree precondition", "Active Codex Git behavior is externally governed"] },
        ],
        identity: [
          { label: "AgentRunId", purpose: "Allocated before foundational execution for run correlation and isolation.", isNot: "Not authorization and not durable active-run state." },
          { label: "ProposalId", purpose: "UUID-backed, nonzero, unique within one run, retained in a per-run seen set, and copied to ToolCallRequest.idempotency_key for duplicate dispatch detection and correlation.", isNot: "Not authentication, authorization, a transaction ID, durable idempotency, or global replay defense." },
          { label: "Active approval identity", purpose: "Binds the authenticated owner, bridge generation, exact pending protocol request, expiry, and one decision.", isNot: "Not inferable from model or user wording." },
        ],
        testing: [
          { label: "Deterministic infrastructure", items: ["Scripted model provider", "Fake tool executor", "Fake / fixed clock", "Fixed IDs", "In-memory audit sink", "Fake Codex App Server stream", "Fake remote transport", "Fake browser provider"] },
          { label: "Proven behaviors", items: ["Exact model → tool → model sequence", "Exactly-once proposal dispatch", "Duplicate and repeated-action rejection", "Deadline and cancellation checkpoints", "Provider cleanup", "Controlled-clock audit ordering", "Protocol event classification", "Stale-generation and wrong-owner rejection", "Thread resume and recovery"] },
        ],
        validation: [{ label: "Python tests collected", value: "892" }, { label: "Passed", value: "889", emphasis: true }, { label: "Skipped", value: "3" }],
        validationNotes: ["The three skips concern unavailable Windows symlink creation on the forensic host.", "Android / Gradle tests were not executed in this forensic pass.", "No live Codex, OpenAI, Gmail, Tailscale, browser, or Android-device integration was executed.", "This is not a 100% tested or production-proven claim."],
        failureModes: [
          { mode: "Unknown local tool", response: "Safe failure before resolution", correctness: "No execution", recovery: "Model may receive bounded failure observation" },
          { mode: "Policy denial", response: "Broker stops before resolution", correctness: "No side effect", recovery: "Denied result" },
          { mode: "Malformed / invalid proposal", response: "Runtime validation rejects it", correctness: "No dispatch", recovery: "Safe run failure" },
          { mode: "Duplicate proposal", response: "Per-run seen set detects it", correctness: "No redispatch", recovery: "Run terminates safely" },
          { mode: "Provider / tool failure", response: "Run failure or safe ToolFailure result", correctness: "Cleanup attempted; tool failures may continue within limits", recovery: "Bounded observation" },
          { mode: "Deadline / cancellation checkpoint", response: "No later step begins", correctness: "Checked before model and tool steps", recovery: "In-flight work is not universally interrupted" },
          { mode: "Filesystem / Git boundary violation", response: "Workspace or repository validation rejects it", correctness: "No authorized operation", recovery: "Safe failure" },
          { mode: "Shell timeout", response: "Timeout maps to a failure result", correctness: "Call returns bounded status", recovery: "Descendant-tree cleanup is not proven" },
          { mode: "Codex protocol failure", response: "Restart and thread resume attempted", correctness: "Protocol state is re-established or failed", recovery: "STARTING / WORKING or FAILED" },
          { mode: "Unknown / stale Codex event", response: "Unknown request declined; stale event rejected or ignored", correctness: "Current turn identity remains authoritative", recovery: "Unknown request fails the turn" },
          { mode: "Wrong-owner / expired approval", response: "Decision denied", correctness: "Pending request remains structurally protected", recovery: "No unauthorized resolution" },
        ],
        persistence: [
          { label: "Durable when wired", items: ["SQLite tasks", "SQLite audit_events", "WAL + per-operation commits", "Versioned Codex thread-reference JSON"] },
          { label: "Volatile in active composition", items: ["Remote task handles + streamed chunks", "Pending approvals", "Bridge generation + active turn", "Replay nonce set", "Active remote audit sink"] },
          { label: "Not completely durable", items: ["Active conversation record", "Task results", "Approval decisions", "Proposal state"] },
        ],
        auditLimitation: ["A requested/policy audit failure before local execution prevents the tool from running.", "A tool side effect may succeed and the completion audit append may then fail.", "No transaction spans the OS side effect and audit storage.", "SQLite ordering uses timestamp plus ID; there is no explicit monotonically increasing causal sequence number."],
        tradeoffs: [
          { title: "Single serialized Codex thread", decision: "Prefer one active turn for simpler thread, approval, and protocol-state correctness.", tradeoff: "Head-of-line blocking and limited throughput." },
          { title: "In-memory active task state", decision: "Keep local task orchestration simple.", tradeoff: "Restart loses tasks, approvals, and replay state." },
          { title: "External Codex tool execution", decision: "Gain broad capability without implementing every tool locally.", tradeoff: "JARVIS cannot independently enumerate or prove every active tool boundary." },
          { title: "Local policy broker", decision: "Maintain an ordered, strongly testable authority boundary.", tradeoff: "It is not universal over active Codex tools." },
          { title: "Structured shell argv", decision: "Avoid implicit shell parsing with shell=False.", tradeoff: "This does not sandbox executable authority." },
          { title: "Deterministic fakes", decision: "Make exact protocol and runtime invariants reproducible.", tradeoff: "Fake-tested integration is not live external-service proof." },
        ],
        limitations: ["Two architectures coexist; their guarantees are not interchangeable.", "Active Codex tools do not pass through the local ToolBroker.", "External Codex sandbox/tool enforcement is configured but not independently proven by JARVIS.", "Approval previews are generic.", "Remote audit, task, replay, and approval state are volatile; SQLite is not the active default remote audit store.", "No transaction spans OS effects and audit completion.", "Foundational approval-required calls cannot resume as approved execution.", "Successful local tool output is not returned to the foundational model.", "Local shell has broad ambient authority if enabled; filesystem operations lack comprehensive resource limits.", "Windows symlink/reparse coverage is incomplete.", "Foundational cancellation/deadline does not interrupt every in-flight call.", "Multi-run mutation isolation is unproven.", "No CI workflow and no live external-service validation were present in the forensic pass.", "Android tests were not executed in the forensic pass.", "Production secret rotation, rate limiting, durable replay, and multi-client tenancy are not demonstrated.", "The external Codex tool inventory is unknown to this repository.", "JARVIS does not claim to solve prompt injection; malicious repository, web, or email content may still influence model reasoning."],
        retrospective: ["The important problem is not making an AI capable of more actions. It is deciding who is allowed to turn intent into side effect.", "The current system meaningfully separates natural-language intent, authenticated authorization, provider protocol state, local policy, workspace boundaries, and OS-facing execution.", "The next architectural problem is that the foundational local policy broker and the active Codex execution path provide different guarantees. Unifying those authority models is a future direction, not implemented work."],
      },
    },
  },
  {
    slug: "ticketforge", index: "02", title: "TicketForge", shortTitle: "TicketForge", category: "High-Contention Ticket Allocation System",
    summary: "A finite-inventory allocation service built to preserve durable ownership and idempotent outcomes under concurrent, retried, and multi-process purchase attempts.",
    status: "case-study", accent: "split",
    metrics: [{ label: "Purchase attempts", value: "50,000", emphasis: true }, { label: "Durable owners", value: "100" }, { label: "Oversell detected", value: "0" }, { label: "Average attempt rate", value: "3,066.3/s" }, { label: "All-attempt P99", value: "427.938 ms" }],
    themes: ["PostgreSQL", "Idempotency", "Admission control", "Recovery"],
    dossier: {
      role: "Personal engineering project",
      mission: "Allocate finite inventory without losing durable ownership or idempotent outcomes when concurrent, retried, and multi-process purchase attempts collide.",
      context: "This is a failure-driven local systems experiment: PostgreSQL holds the shared correctness state while independent Go seller processes contend for a fixed sale. The central story is reproduce failure → change the architecture → re-measure the result.",
      constraints: ["100-ticket finite inventory", "One durable outcome per sale-scoped request ID", "No false sold-out while inventory is merely locked", "Cross-seller retry convergence", "Explicit overload shedding before database access"],
      architecture: {
        description: "The load generator routes deterministically and directly to three sellers. There is no load balancer, Redis, distributed lock service, or message broker. PostgreSQL is the shared source of truth for sale lifecycle, request outcomes, ticket ownership, locks, and constraints; listeners, permit channels, timers, and pgx pools are process-local.",
        layout: "fan-in",
        nodes: [{ id: "load", label: "Load generator", detail: "Deterministic direct routing" }, { id: "seller-a", label: "Seller A", detail: "Admission 20 · pool 22" }, { id: "seller-b", label: "Seller B", detail: "Admission 20 · pool 22" }, { id: "seller-c", label: "Seller C", detail: "Admission 20 · pool 22" }, { id: "postgres", label: "PostgreSQL", detail: "Sale lifecycle · request ledger · ticket ownership · locks + constraints" }],
        edges: [{ from: "load", to: "seller-a" }, { from: "load", to: "seller-b" }, { from: "load", to: "seller-c" }, { from: "seller-a", to: "postgres" }, { from: "seller-b", to: "postgres" }, { from: "seller-c", to: "postgres" }],
      },
      executionFlow: ["POST /buy", "Validate buyer_id + request_id", "Timed admission", "READ COMMITTED transaction", "FOR SHARE lock on current_sale", "Claim (sale_id, request_id)", "Existing request? replay durable outcome", "New request? allocate", "FOR UPDATE SKIP LOCKED fast path", "No candidate? blocking FOR UPDATE fallback", "Conditional buyer_id IS NULL ownership update", "Finalize durable request outcome", "COMMIT", "HTTP response"],
      decisions: [
        { title: "PostgreSQL-mediated correctness", pressure: "Independent seller processes can attempt the same finite inventory concurrently.", decision: "Use PostgreSQL transactions, row locks, and constraints as the shared durable coordination boundary.", tradeoff: "The database becomes the primary availability boundary." },
        { title: "Durable request ledger", pressure: "A retry must not consume another ticket, even through a different seller or after a restart.", decision: "Persist purchase_requests with PRIMARY KEY (sale_id, request_id) and a durable purchased or sold-out outcome.", tradeoff: "One retained row exists for every logical outcome." },
        { title: "SKIP LOCKED + blocking fallback", pressure: "A SKIP LOCKED miss can mean either sold out or temporarily locked inventory.", decision: "Allocate in parallel with FOR UPDATE SKIP LOCKED, then use a blocking FOR UPDATE fallback before committing sold-out.", why: "The fallback establishes authoritative exhaustion rather than treating lock contention as sold-out.", tradeoff: "Near exhaustion, the worst case performs two allocation queries." },
        { title: "Process-local timed admission", pressure: "Slow database work can consume every pool connection and starve status traffic.", decision: "Use buyPermits chan struct{} after validation and before Store.Buy, with limit 20, 250 ms wait, and pgx pool max 22 per seller.", tradeoff: "It preserves nominal two-connection pool headroom, but is not global admission and can return HTTP 503 to legitimate attempts." },
        { title: "Transaction semantics", pressure: "The allocator must distinguish an uncommitted failure from an outcome that may have committed but could not be confirmed.", decision: "Use READ COMMITTED, defer rollback for non-commit paths, and return ErrOutcomeUnknown on commit error.", why: "There is no transaction retry loop or deadlock/serialization retry; callers must resolve an ambiguous result through idempotent replay." },
      ],
      failureModes: [
        { mode: "Pool-starvation progression", fault: "A BEFORE INSERT purchase_requests trigger ran pg_sleep(10). Before admission, 44 concurrent requests exhausted a 22-connection pool; two status requests exceeded 2-second client deadlines.", observation: "Slow claims consumed the pool, so control-plane status traffic could not obtain a database connection.", mitigation: "Admission was set to 20 per seller below pool max 22, preserving nominal headroom; a 250 ms permit wait bounded waiter residence.", retest: "500 attempts at concurrency 500: 20 purchases, 480 explicit HTTP 503s; peak 180 permit waiters and 424 goroutines.", result: "Waiters returned to zero by 801.837 ms. Status remained responsive. Six status probes in the headroom experiment completed in approximately 4.014–42.857 ms." },
        { mode: "Post-commit response suppression", fault: "A drop-response proxy sat between client and Seller A. It observed Seller A's upstream HTTP 201 for ticket 1, then intentionally closed the downstream connection without delivering it.", observation: "The client received no HTTP status despite a committed purchase.", mitigation: "Retry the same logical request through Seller B; PostgreSQL purchase_requests resolves the durable identity.", retest: "Seller B returned HTTP 201 with ticket 1 for the same buyer and request ID.", result: "One purchased request row and one ticket owner remained. This is tested response suppression, not proof of arbitrary network-partition semantics; no separate reconciliation service exists." },
        { mode: "Seller B restart", fault: "Seller B was killed while 30 delayed purchases were distributed across Sellers A, B, and C.", observation: "A and C completed 10 purchases each; B's 10 direct clients lost their connections while the other sellers remained available.", mitigation: "Restart B and rely on PostgreSQL's committed ownership and request outcomes rather than process memory.", retest: "B immediately observed 20 durable purchases. Retrying B's 10 interrupted IDs purchased without duplication; a new B purchase also succeeded.", result: "Process-local listeners, permits, and pools disappear on restart; committed PostgreSQL state survives. No reconciliation process was required." },
        { mode: "PostgreSQL local stop/start", fault: "PostgreSQL was stopped during nine active delayed claims.", observation: "All affected buys returned HTTP 503 unavailable; status returned 503 while the database was unavailable; all sellers remained alive and no false sold-out response was observed.", mitigation: "Restart the same local PostgreSQL service and volume. Seller processes were left running.", retest: "The nine IDs were retried through different sellers and succeeded; three additional purchases succeeded.", result: "Final state had no pending or partial state. No circuit breaker, automatic retry, retry backoff, request queue, database HA, or failover behavior was tested." },
      ],
      invariants: [
        { invariant: "One physical ticket per sale / number", database: "PRIMARY KEY (sale_id, ticket_number)", application: "Allocation addresses a ticket inside the locked current sale.", evidence: "Schema and concurrent-purchase integration test." },
        { invariant: "One ticket has at most one owner", database: "One ticket row; purchase_requests has UNIQUE (sale_id, ticket_number).", application: "Conditional ownership update requires buyer_id IS NULL.", evidence: "Concurrent allocation tests and final invariant audit." },
        { invariant: "Finite inventory cannot oversell", database: "Only seeded ticket rows can be assigned.", application: "Sold-out is finalized only after the authoritative blocking fallback.", evidence: "50,000-attempt preserved run: 100 tickets, 100 owners, zero detected overselling." },
        { invariant: "One request ID has one durable outcome per sale", database: "PRIMARY KEY (sale_id, request_id)", application: "First claim wins; later requests replay the stored outcome or conflict on buyer mismatch.", evidence: "Sequential and concurrent duplicate-request tests." },
        { invariant: "Retry cannot consume another ticket", database: "Durable request ledger stores the ticket number for purchased outcomes.", application: "Replay returns the stored ticket rather than allocating again.", evidence: "Duplicate, restart, and response-suppression tests." },
        { invariant: "HTTP 201 follows commit", database: "Purchase request and ticket update commit in one transaction.", application: "Handler emits success only after Store.Buy returns from commit.", evidence: "Response-discard integration scenario." },
        { invariant: "Reset cannot split a buy across sale epochs", database: "current_sale pointer and foreign-keyed sale records.", application: "Buy takes current_sale FOR SHARE; reset takes it FOR UPDATE.", evidence: "Reset and lifecycle integration tests." },
      ],
      reliabilityTitle: "Durable request ledger / idempotency",
      reliability: ["First request claims a pending (sale_id, request_id) ledger entry, then finalizes purchased or sold-out after allocation.", "A duplicate while the original runs is arbitrated by the unique database claim; a completed purchase or sold-out outcome replays durably.", "Same request ID with a different buyer returns an idempotency conflict.", "A pre-commit failure rolls back; a retry may execute normally. A commit error is reported as an unknown outcome rather than a fabricated result.", "Identity is sale-scoped, so the same textual request ID may be reused after a new sale. Cross-instance retries converge through PostgreSQL.", "Phase 7 multi-instance evidence: 75 attempts, 26 logical request IDs, three sellers, 26 request rows, 26 assignments, and every response group agreed on its ticket."],
      performance: { label: "Final experiment // three sellers", methodology: "LOCAL EXPERIMENTAL RUN — NOT PRODUCTION CAPACITY. One preserved Windows/amd64 run using 22 logical CPUs, Go 1.27.1, Docker Server 29.7.2, and PostgreSQL 17.6. Average attempt rate is all HTTP attempts divided by coordinated worker duration; it includes purchased, sold-out, and unavailable responses. P99 is client-observed end-to-end latency across all attempts, from client.Do through response-body read.", metrics: [{ label: "Attempts", value: "50,000" }, { label: "Logical request IDs", value: "37,500" }, { label: "Duplicate attempts", value: "12,500" }, { label: "Load workers", value: "1,000" }, { label: "Sellers", value: "3" }, { label: "Tickets", value: "100" }, { label: "Durable owners", value: "100" }, { label: "Oversell detected", value: "0" }, { label: "Duration", value: "16.306s" }, { label: "Average attempt rate", value: "3,066.3/s" }, { label: "All-attempt P99", value: "427.938 ms" }, { label: "Explicit 503s", value: "115" }, { label: "Transport errors", value: "0" }, { label: "Invariant audit", value: "Pass" }] },
      tradeoffs: ["PostgreSQL-mediated correctness gives durable shared coordination, but makes the database the primary availability boundary.", "Process-local admission is simple and leaves per-seller pool headroom, but aggregate database pressure grows with seller count.", "A timed 250 ms permit wait bounds waiter residence and exposes overload explicitly, but legitimate attempts can receive HTTP 503.", "The durable request ledger enables restart-safe, cross-instance replay including sold-out outcomes, but retains one row per logical outcome.", "SKIP LOCKED plus a blocking fallback enables parallel allocation without false sold-out, but costs a second query in the near-exhaustion case."],
      results: ["The canonical preserved run contained 50,000 purchase attempts, not 50,000 buyers: 37,500 logical request IDs and 12,500 duplicate attempts.", "Across 16.3062881 seconds, all attempts averaged 3,066.3018 attempts/sec; this is not successful-purchase throughput.", "Client-observed all-attempt P99 was 427.9379 ms; it is not a successful-purchase latency claim.", "100 tickets produced 100 unique durable owners with zero detected overselling; 115 responses were explicit HTTP 503 and transport errors were zero."],
      limitations: ["Production topology is not established; there is no PostgreSQL HA/failover test, reverse proxy, or load balancer.", "No authentication, authorization, TLS, or explicit HTTP server timeouts/body limits are implemented.", "Production observability is minimal. Admission is process-local, not globally coordinated, and instantaneous waiter population has no hard count bound.", "This is one preserved local experimental run, not a statistical capacity study: CPU model, RAM, storage, warm-up, variance, and confidence intervals are not claimed."],
      links: [{ label: "View source", href: "https://github.com/ChetanAmritanshu/TicketForge" }, { label: "View evidence", href: "https://github.com/ChetanAmritanshu/TicketForge/tree/main/experiments" }],
      technology: ["Go", "PostgreSQL", "Transactional allocation", "Request-ID idempotency", "Admission control"],
    },
  },
  {
    slug: "trading-square-off", index: "03", title: "Trading Square-Off System", shortTitle: "Square-Off", category: "Production Trading Backend",
    summary: "A Go trading backend built around high-throughput RabbitMQ workflows, idempotency, Redis coordination, and bounded failure handling.",
    status: "production", accent: "crimson",
    metrics: [{ label: "Volume", value: "5K+ trades/min", emphasis: true }, { label: "Latency", value: "Sub-120 ms P95" }, { label: "Availability", value: "99.9%+" }, { label: "DB writes", value: "~40% reduction" }],
    themes: ["Go", "RabbitMQ", "Redis", "Circuit breakers"],
    dossier: {
      role: "Backend engineering", mission: "Process high-volume square-off workflows with controlled latency and isolated failure behavior.",
      disclosure: "Selected implementation and operational details are intentionally omitted due to client confidentiality.",
      context: "The approved professional scope is limited to system-level throughput, resilience mechanisms, and coordination technology; confidential trading logic is intentionally excluded.",
      constraints: ["5K+ trades per minute", "Sub-120 ms P95", "99.9%+ availability", "Idempotent workflow handling"],
      decisions: [{ title: "RabbitMQ workflows", decision: "Use RabbitMQ for asynchronous workflows." }, { title: "Idempotency and recovery", decision: "Use idempotency, retries, and dead-letter queues." }, { title: "Redis coordination", decision: "Use Redis coordination and locking." }, { title: "Fault isolation", decision: "Use circuit breakers, timeouts, and fault isolation." }],
      reliability: ["Retries", "Dead-letter queues", "Circuit breakers", "Timeouts", "Fault isolation", "99.9%+ availability"],
      performance: { label: "Approved production evidence", metrics: [{ label: "Processing volume", value: "5K+ trades/min" }, { label: "P95 latency", value: "Sub-120 ms" }, { label: "Availability", value: "99.9%+" }, { label: "DB writes", value: "~40% reduction" }] },
      results: ["Processed more than 5,000 trades per minute.", "Maintained sub-120 ms P95 latency.", "Reduced database writes by approximately 40%.", "Achieved 99.9%+ availability."],
      technology: ["Go", "RabbitMQ", "Redis", "Dead-letter queues", "Circuit breakers"],
    },
  },
  {
    slug: "ai-sales-advisor", index: "04", title: "AI-Powered Sales Advisor", shortTitle: "Sales Advisor", category: "GenAI Retrieval System",
    summary: "A Python and GenAI product-discovery system using OpenSearch across a catalog of more than 50,000 products.",
    status: "production", accent: "cyan",
    metrics: [{ label: "Catalog", value: "50K+ products", emphasis: true }, { label: "Search latency", value: "30% reduction" }, { label: "Search", value: "OpenSearch" }],
    themes: ["Python", "GenAI", "Retrieval", "OpenSearch"],
    dossier: {
      role: "Backend engineering", mission: "Improve product-scale information access across a catalog of more than 50,000 products.",
      disclosure: "Selected implementation and operational details are intentionally omitted due to client confidentiality.",
      context: "This case study is intentionally constrained to verified retrieval, search, scale, and latency facts.",
      constraints: ["50K+ products", "Product discovery", "Search latency"],
      decisions: [{ title: "OpenSearch retrieval", decision: "Use OpenSearch for product search and retrieval." }, { title: "Python / GenAI backend", decision: "Build the product-discovery backend with Python and GenAI capabilities." }],
      performance: { label: "Approved search evidence", metrics: [{ label: "Product catalog", value: "50K+ products" }, { label: "Search latency", value: "30% reduction" }] },
      results: ["Supported product discovery across more than 50,000 products.", "Reduced search latency by 30%."],
      retrospective: ["Model provider, prompting, ranking, embeddings, RAG design, and evaluation methodology are not present in the verified content."],
      technology: ["Python", "GenAI", "OpenSearch", "Search", "Retrieval"],
    },
  },
] as const satisfies readonly Project[];

export function findProject(slug: string): Project | undefined { return projects.find((project) => project.slug === slug); }
export function adjacentProjects(slug: string): { previous: Project; next: Project } | undefined {
  const index = projects.findIndex((project) => project.slug === slug);
  if (index < 0) return undefined;
  return { previous: projects[(index - 1 + projects.length) % projects.length], next: projects[(index + 1) % projects.length] };
}
